# Site settings
title: lxHive - a fast and lightweight open source xAPI LRS
email: support@g3i.com.au
url: http://localhost:4000
baseurl: ""
description: "lxHive is a fast and lightweight open source xAPI conformant Learning Record Store (LRS). lxHive logs and returns activity statements as defined in the Experience API specification."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 'rgb(255, 164, 0)'
  primary-bg: 'rgb(255, 164, 0)'
  body: 'rgb(85, 86, 90)'
  body-bg: 'rgb(255, 255, 255)'
  white-alpha-3: 'rgba(255,255,255,.3)'
  white-alpha-1: 'rgba(255,255,255,.1)'
  links: 'rgba(0, 131, 215, 1)'
  links-hover: 'rgba(0, 131, 215, .5)'
  selection: '#fcfcfc'
  light-grey: '#f3f3f3'

fonts:
  main: '"Roboto Condensed", sans-serif, Helvetica, Arial, sans-serif'

formats:
  lxHive: '<span class="lxHive inline">lx<strong>Hive</strong></span>'
  lxHive-hl: '<span class="lxHive hl"><span class="light">lx</span>Hive</span>'

# Footer settings
footer: G3i Pty Ltd

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: 'Issues'
    url: 'https://github.com/g3i/lxHive/issues'
    icon: '<i class="fa fa-github"></i>'
  - title: Enquiries
    url: 'https://g3i.com.au/contact-us/'
    'icon': '<i class="fa fa-envelope"></i>'

# GA and linked data
analytics:
  key: 'UA-63908505-1'

# Build settings
markdown: kramdown
permalink: pretty
